theme: jekyll-theme-minimal
logo: /assets/images/ibrahim-netto.jpeg
title: Ibrahim Netto - Full-Stack Developer
description: Full-stack developer, system analyst and partner at Advisor Tecnologia. Specialized in web and hybrid application development with Node.js as back-end, single-page applications with Angular 5 for front-end and MongoDB as database. Graduated in Computer Science from FEI University and also graduated in Marketing from ESPM college.
google_analytics: UA-117581851-1